name: Modify Headers

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  update-headers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch data from API
      run: |
        # Replace with your actual API endpoint
        API_URL="https://justmysocks5.net/members/getbwcounter.php?service=531532&id=0ffb1cda-1854-43ec-88c2-8d63cd32f280"
        
        # Use curl to fetch the data and jq to parse it
        RESPONSE=$(curl -s "$API_URL")
        DOWNLOAD=$(echo $RESPONSE | jq -r '.bw_counter_b')
        TOTAL=$(echo $RESPONSE | jq -r '.monthly_bw_limit_b')
        DAYS_TO_EXPIRE=$(echo $RESPONSE | jq -r '.bw_reset_day_of_month')
        
        # Calculate the Unix timestamp for expiry
        EXPIRY_TIMESTAMP=$(date -d "+$DAYS_TO_EXPIRE days" +%s)
        
        # Create the combined header value
        HEADER_VALUE="upload=0; download=$DOWNLOAD; total=$TOTAL; expire=$EXPIRY_TIMESTAMP"
        
        # Modify the _headers file
        echo "/subscribe" > _headers
        echo "  Content-Disposition: attachment; filename=mcca.yaml" >> _headers
        echo "  Combined-Key: $HEADER_VALUE" >> _headers

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _headers
        git commit -m "Modify _headers via GitHub Action"
        git push
