name: Modify Headers

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  update-headers:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch data from API
      run: |
        # Replace with your actual API endpoint
        API_URL="https://justmysocks5.net/members/getbwcounter.php?service=531532&id=0ffb1cda-1854-43ec-88c2-8d63cd32f280"
        
        # Use curl to fetch the data and jq to parse it
        RESPONSE=$(curl -s "$API_URL")
        echo "API Response: $RESPONSE"
        KEYA=$(echo $RESPONSE | jq -r '.monthly_bw_limit_b')
        KEYB=$(echo $RESPONSE | jq -r '.bw_counter_b')
        KEYC=$(echo $RESPONSE | jq -r '.bw_reset_day_of_month')
        
        # Modify the _headers file
        echo "/subscribe" > _headers
        echo "  Content-Disposition: attachment; filename=mcca.yaml" >> _headers
        echo "  keya: $KEYA" >> _headers
        echo "  keyb: $KEYB" >> _headers
        echo "  keyc: $KEYC" >> _headers

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _headers
        git commit -m "Modify _headers via GitHub Action"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
